# Generated by Django 4.2.16 on 2024-10-06 15:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
