# Generated by Django 4.2.16 on 2024-10-04 13:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_home_options_home_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
