# Generated by Django 4.2.16 on 2024-10-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationrequest',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='approved',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved')], default=0),
        ),
    ]
