# Generated by Django 4.2.16 on 2024-10-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservationrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
