# Generated by Django 4.2.16 on 2024-10-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_reservationcontent_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrequest',
            name='reservation_date_time',
            field=models.CharField(choices=[('2024-10-25 14:30', 'October 25, 2024, 2:30 PM'), ('2024-10-25 15:00', 'October 25, 2024, 3:00 PM'), ('2024-10-25 15:30', 'October 25, 2024, 3:30 PM')], max_length=20),
        ),
    ]
