# Generated by Django 4.2.16 on 2024-10-05 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservationrequest_reservation_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationrequest',
            name='reservation_date_time',
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='reservation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='reservation_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
